### ISSUE TITLE
Discussion on pg_bouncer

### ISSUE THREAD

**Issue by LamaAni** [LamaAni/PGXL-HELM#20]
@sstubbs 

Hi, 

Once considering pg_bouncer fully, I am thinking about separating the pg_bouncer to a different chart, or use an existing chart. 

Existing charts:
https://github.com/cradlepoint/kubernetes-helm-chart-pgbouncer

What do you think?

**Comment by stephenstubbs** [comment]
This makes sense. Ideally I want developers to manage their own kubernetes deployments in my environment which is why I was worried about security and liked the idea of it being integrated behind the service. I am going to try rather try using something like this https://blog.darkedges.com/2019/01/17/configuring-zero-trust-with-kubernetes-Iistio-and-calico/ to make sure containers can only connect to the pgbouncer pod. 

The pgbouncer deployment I have seems to work fine for now. Just doing a bit more testing and will do a pr just so its there if anyone wants it. I'm not sure I actually need helm for my use as pgbouncer is quite simple to setup and I want to use version 1.11 as it support scram-sha. Most containers and helm charts I have looked at use quite an old version of it.  

This was the only container I found using 1.11 https://hub.docker.com/r/pgbouncer/pgbouncer as most the others I looked at were installing it via distro package managers and it will be some time before 1.11 is available in those.

**Comment by LamaAni** [comment]
Please do add that PR.

We agree then. I might create a pg-bouncer image+helm chart by myself if that is the case. I am looking forward to trying that. 

I would note that most charts allow you to change the image. If I get time to test this I will let you know.

**Comment by LamaAni** [comment]
That said, there is one more security concern we can add to the chart, 
pg_hba
See new feature enhancement I posted. 

I am not sure if it would be more useful to keep security on the kubernetes level and not enter postgres level directly. At some point, though, it would be needed that all kubernetes pods for the database will only allow connections through the svc.

**Comment by stephenstubbs** [comment]
Sure I will look at that other issue just going to finish pgbouncer with vault pr first. Here is the pr for pgbouncer without vault. https://github.com/LamaAni/PGXL-HELM/pull/26/commits/96f5618267a0b3f6dd1f8c841672756d856f573d

The image does support env variables to create a config but it expects like most images I've looked at to not use auth query and rather manually add dbs and users unless I've missed something. This is why I'm creating the config in the deployment command.

**Comment by LamaAni** [comment]
I see. Ok in this case we can do a PR to that image and add this as a feature request. Then, depending on the way they respond we will know if we need to create another image. 

Appologies, I have been working on the base and mostly not looking at pg_bouncer yet.

**Comment by LamaAni** [comment]
@sstubbs 
Do the init scripts solve this issue?

**Comment by stephenstubbs** [comment]
Yes perfectly. Can we leave this issue though as now that they merged in I need to get the pgbouncer without vault example updated to use it too. Once done later today I will close this.

**Comment by LamaAni** [comment]
Awsome
