### ISSUE TITLE
GTM Proxy Service

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#25]
I noticed that the gtm proxy service svc-pxy is a LoadBalancer. Is this required? If not it's probably safer to use ClusterIP as it shouldn't be accessed remotely.

**Comment by LamaAni** [comment]
@sstubbs 
This is an oversight on my part - it was a test that should have not been committed to master. You are correct. I will add a pr to correct this once I have a bit of time.

Would you mind doing PR reviews? Since you are starting to use this, I would prefer a second look on things I put into master.

**Comment by stephenstubbs** [comment]
ok sounds good.

**Comment by LamaAni** [comment]
Please see PR here, I assigned you to it if thats ok. 
https://github.com/LamaAni/PGXL-HELM/pull/27

**Comment by LamaAni** [comment]
Resolved by PR.
